### ISSUE TITLE
Monitor map changes

### ISSUE THREAD

**Issue by sanfern** [l3af-project/l3afd#201]
Sample monitor map promQL format:

l3afd_NFMonitorMap{host="l3af-local-test",map_name="rl_drop_count_map_0_scalar",network_function="ratelimiting"} 1
l3afd_NFMonitorMap{host="l3af-local-test",map_name="rl_recv_count_map_0_max-rate",network_function="ratelimiting"} 21

1. Update monitor map with interface name tags.
2. Rename network_function to ebpf_program.

**Comment by DecFox** [comment]
Hey @sanfern, I'd like to take up this issue if that's alright.
