### ISSUE TITLE
Configure payload to have no full path for program map names.

### ISSUE THREAD

**Issue by sanfern** [l3af-project/l3afd#33]
The map name looks like the full path, not just the map name itself.
Could we just make it the map name itself (i.e., "xdp_cl_ingress_next_prog" where path "/sys/fs/bpf/" is implied on Linux), since the path will be different between Linux vs Windows. That is, allow relative paths not just absolute paths.

**Comment by dthaler** [comment]
@sanfern is about 50% done with this one so far
