### ISSUE TITLE
Problem while Redirecting TCP packet

### ISSUE THREAD

**Issue by Monk3yDLuffy** [l3af-project/l3afd#43]
Hi everyone we are making xdp code redirecting, and while trying to send send TCP packets we face some problem while we ping packets from one container to another. 
I tried redirecting packets send to one docker instance to another container using xdp. I followed xdp_tutorial to reroute packet, and created 2 dockers to redirect packet from one docker to another. I am getting the packet at target docker but when i run ping `172.17.0.2` on source machine/sender ,I got Destination Host Unreachable on system.

For system details and output refer issue i raised at [xdp_tutorial repo.](https://github.com/xdp-project/xdp-tutorial/issues/279)

What additions should i make to get TCP rerouting to work

**Comment by jniesz** [comment]
Closing this issue as it does not relate to l3afd, which is the orchestrator for ebpf programs and chaining of programs.
