### ISSUE TITLE
Add granular APIs to add, delete ebpf programs on a node

### ISSUE THREAD

**Issue by satyaranjanp** [l3af-project/l3afd#57]
Currently L3AFD supports GET API to get the eBPF programs running on a node and UPDATE API to manage the eBPF programs on a node. Instead of using only UPDATE API for program management, we can segregate the eBPF program orchestration by supporting the below APIs also:
1. ADD: Starts a new eBPF program on a node
2. DELETE: Remove an existing eBPF program from a node

And, we can limit the current scope of UPDATE API to only update/patch configuration of existing eBPF programs on a node.

**Comment by dahavey** [comment]
@dthaler - We have decided this is a good first issue. Could you please add the tag?

**Comment by sanfern** [comment]
Implemented - PR 76
